# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x07message\"F\n\x12SendMessageRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\x12\x10\n\x08reply_to\x18\x03 \x01(\t\"Q\n\x13SendMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nmessage_id\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\"&\n\x15ReceiveMessageRequest\x12\r\n\x05topic\x18\x01 \x01(\t\"s\n\x16ReceiveMessageResponse\x12\x13\n\x0bhas_message\x18\x01 \x01(\x08\x12\x12\n\nmessage_id\x18\x02 \x01(\t\x12\r\n\x05topic\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\t\x12\x10\n\x08reply_to\x18\x05 \x01(\t\":\n\x14\x43haracterDataRequest\x12\x14\n\x0c\x63haracter_id\x18\x01 \x01(\x05\x12\x0c\n\x04gold\x18\x02 \x01(\x05\"\\\n\x15\x43haracterDataResponse\x12\x14\n\x0c\x63haracter_id\x18\x01 \x01(\x05\x12\x0c\n\x04gold\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t2\xb3\x01\n\x14MessageBrokerService\x12H\n\x0bSendMessage\x12\x1b.message.SendMessageRequest\x1a\x1c.message.SendMessageResponse\x12Q\n\x0eReceiveMessage\x12\x1e.message.ReceiveMessageRequest\x1a\x1f.message.ReceiveMessageResponse2m\n\x14\x43haracterDataService\x12U\n\x14ProcessCharacterData\x12\x1d.message.CharacterDataRequest\x1a\x1e.message.CharacterDataResponseB(\n\x16\x63om.microservices.grpcB\x0cMessageProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.microservices.grpcB\014MessageProtoP\001'
  _globals['_SENDMESSAGEREQUEST']._serialized_start=26
  _globals['_SENDMESSAGEREQUEST']._serialized_end=96
  _globals['_SENDMESSAGERESPONSE']._serialized_start=98
  _globals['_SENDMESSAGERESPONSE']._serialized_end=179
  _globals['_RECEIVEMESSAGEREQUEST']._serialized_start=181
  _globals['_RECEIVEMESSAGEREQUEST']._serialized_end=219
  _globals['_RECEIVEMESSAGERESPONSE']._serialized_start=221
  _globals['_RECEIVEMESSAGERESPONSE']._serialized_end=336
  _globals['_CHARACTERDATAREQUEST']._serialized_start=338
  _globals['_CHARACTERDATAREQUEST']._serialized_end=396
  _globals['_CHARACTERDATARESPONSE']._serialized_start=398
  _globals['_CHARACTERDATARESPONSE']._serialized_end=490
  _globals['_MESSAGEBROKERSERVICE']._serialized_start=493
  _globals['_MESSAGEBROKERSERVICE']._serialized_end=672
  _globals['_CHARACTERDATASERVICE']._serialized_start=674
  _globals['_CHARACTERDATASERVICE']._serialized_end=783
# @@protoc_insertion_point(module_scope)
