# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import message_pb2 as message__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in message_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MessageBrokerServiceStub(object):
    """Message Broker Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
                '/message.MessageBrokerService/SendMessage',
                request_serializer=message__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=message__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.ReceiveMessage = channel.unary_unary(
                '/message.MessageBrokerService/ReceiveMessage',
                request_serializer=message__pb2.ReceiveMessageRequest.SerializeToString,
                response_deserializer=message__pb2.ReceiveMessageResponse.FromString,
                _registered_method=True)


class MessageBrokerServiceServicer(object):
    """Message Broker Service
    """

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageBrokerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=message__pb2.SendMessageRequest.FromString,
                    response_serializer=message__pb2.SendMessageResponse.SerializeToString,
            ),
            'ReceiveMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveMessage,
                    request_deserializer=message__pb2.ReceiveMessageRequest.FromString,
                    response_serializer=message__pb2.ReceiveMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'message.MessageBrokerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('message.MessageBrokerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessageBrokerService(object):
    """Message Broker Service
    """

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/message.MessageBrokerService/SendMessage',
            message__pb2.SendMessageRequest.SerializeToString,
            message__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/message.MessageBrokerService/ReceiveMessage',
            message__pb2.ReceiveMessageRequest.SerializeToString,
            message__pb2.ReceiveMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CharacterDataServiceStub(object):
    """Character Data Service (for task-service to voting-service communication)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessCharacterData = channel.unary_unary(
                '/message.CharacterDataService/ProcessCharacterData',
                request_serializer=message__pb2.CharacterDataRequest.SerializeToString,
                response_deserializer=message__pb2.CharacterDataResponse.FromString,
                _registered_method=True)


class CharacterDataServiceServicer(object):
    """Character Data Service (for task-service to voting-service communication)
    """

    def ProcessCharacterData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CharacterDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessCharacterData': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessCharacterData,
                    request_deserializer=message__pb2.CharacterDataRequest.FromString,
                    response_serializer=message__pb2.CharacterDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'message.CharacterDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('message.CharacterDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CharacterDataService(object):
    """Character Data Service (for task-service to voting-service communication)
    """

    @staticmethod
    def ProcessCharacterData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/message.CharacterDataService/ProcessCharacterData',
            message__pb2.CharacterDataRequest.SerializeToString,
            message__pb2.CharacterDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
